<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Request;

/**
 * PlanMttoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanMttoRepository extends EntityRepository {

    public function listarDQL() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->addSelect('P')
                ->from($this->getClassName(), 'P');
        return $qb;
    }

    public function filtrar(Request $request) {
        $qb = new QueryBuilder($this->getEntityManager());
        $qb
                ->select("P,TP")
                ->from($this->getClassName(), "P")
                ->leftJoin("P.tipoPrioridad", "TP");

        if ($request->request->get("searchPhrase") != null) {
            $search = $request->request->get("searchPhrase");
            $qb->where($qb->expr()->like("P.frecuencia", $qb->expr()->literal("%" . $search . "%")));
            $qb->orWhere($qb->expr()->like("P.duracion", $qb->expr()->literal("%" . $search . "%")));
            $qb->orWhere($qb->expr()->like("TP.prioridad", $qb->expr()->literal("%" . $search . "%")));
        }
        if ($request->request->get("sort") != null) {
            $orden = $request->request->get("sort");
            foreach ($orden as $key => $value) {
                $qb->orderBy("P." . $key, $value);
            }
        }
        return $qb;
    }

}
