<?php

namespace GEMA\gemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProPerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProPerRepository extends EntityRepository
{
    
    
}
