gema:
    resource: "@gemaBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'