<?php

namespace Proxies\__CG__\GEMA\gemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Actividad extends \GEMA\gemaBundle\Entity\Actividad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'id', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'tipoActividad', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'planMtto', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'actividad');
        }

        return array('__isInitialized__', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'id', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'tipoActividad', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'planMtto', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Actividad' . "\0" . 'actividad');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Actividad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setActividad($actividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActividad', array($actividad));

        return parent::setActividad($actividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividad', array());

        return parent::getActividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlan(\GEMA\gemaBundle\Entity\TipoActividad $plan = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlan', array($plan));

        return parent::setPlan($plan);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlan', array());

        return parent::getPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoActividad(\GEMA\gemaBundle\Entity\TipoActividad $tipoActividad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoActividad', array($tipoActividad));

        return parent::setTipoActividad($tipoActividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoActividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoActividad', array());

        return parent::getTipoActividad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanMtto(\GEMA\gemaBundle\Entity\PlanMtto $planMtto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanMtto', array($planMtto));

        return parent::setPlanMtto($planMtto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanMtto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanMtto', array());

        return parent::getPlanMtto();
    }

}
