<?php

namespace Proxies\__CG__\GEMA\gemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Herramienta extends \GEMA\gemaBundle\Entity\Herramienta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'id', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'nombre', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'costoUnitario', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'depreciacionDiaria', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'norma', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'ProHers');
        }

        return array('__isInitialized__', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'id', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'nombre', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'costoUnitario', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'depreciacionDiaria', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'norma', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\Herramienta' . "\0" . 'ProHers');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Herramienta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostoUnitario($costoUnitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostoUnitario', array($costoUnitario));

        return parent::setCostoUnitario($costoUnitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostoUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostoUnitario', array());

        return parent::getCostoUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepreciacionDiaria($depreciacionDiaria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepreciacionDiaria', array($depreciacionDiaria));

        return parent::setDepreciacionDiaria($depreciacionDiaria);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepreciacionDiaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepreciacionDiaria', array());

        return parent::getDepreciacionDiaria();
    }

    /**
     * {@inheritDoc}
     */
    public function setNorma($norma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNorma', array($norma));

        return parent::setNorma($norma);
    }

    /**
     * {@inheritDoc}
     */
    public function getNorma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNorma', array());

        return parent::getNorma();
    }

    /**
     * {@inheritDoc}
     */
    public function addProHer(\GEMA\gemaBundle\Entity\ProHer $proHers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProHer', array($proHers));

        return parent::addProHer($proHers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProHer(\GEMA\gemaBundle\Entity\ProHer $proHers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProHer', array($proHers));

        return parent::removeProHer($proHers);
    }

    /**
     * {@inheritDoc}
     */
    public function getProHers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProHers', array());

        return parent::getProHers();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
