<?php

namespace Proxies\__CG__\GEMA\gemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrdenTrabajo extends \GEMA\gemaBundle\Entity\OrdenTrabajo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'id', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'nombre', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'planMtto', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'procedimientos', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'costoTotal', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'tiempoTotal', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'cumplida');
        }

        return array('__isInitialized__', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'id', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'nombre', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'planMtto', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'procedimientos', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'costoTotal', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'tiempoTotal', '' . "\0" . 'GEMA\\gemaBundle\\Entity\\OrdenTrabajo' . "\0" . 'cumplida');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrdenTrabajo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanMtto(\GEMA\gemaBundle\Entity\PlanMtto $planMtto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanMtto', array($planMtto));

        return parent::setPlanMtto($planMtto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanMtto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanMtto', array());

        return parent::getPlanMtto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function updateCostos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateCostos', array());

        return parent::updateCostos();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostoTotal($costoTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostoTotal', array($costoTotal));

        return parent::setCostoTotal($costoTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostoTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostoTotal', array());

        return parent::getCostoTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function addProcedimiento(\GEMA\gemaBundle\Entity\Procedimiento $procedimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProcedimiento', array($procedimientos));

        return parent::addProcedimiento($procedimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProcedimiento(\GEMA\gemaBundle\Entity\Procedimiento $procedimientos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProcedimiento', array($procedimientos));

        return parent::removeProcedimiento($procedimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcedimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcedimientos', array());

        return parent::getProcedimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiempoTotal($tiempoTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiempoTotal', array($tiempoTotal));

        return parent::setTiempoTotal($tiempoTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiempoTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiempoTotal', array());

        return parent::getTiempoTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCumplida($cumplida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCumplida', array($cumplida));

        return parent::setCumplida($cumplida);
    }

    /**
     * {@inheritDoc}
     */
    public function getCumplida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCumplida', array());

        return parent::getCumplida();
    }

    /**
     * {@inheritDoc}
     */
    public function removePlanMtto(\GEMA\gemaBundle\Entity\PlanMtto $planMtto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlanMtto', array($planMtto));

        return parent::removePlanMtto($planMtto);
    }

}
